/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndktestapplication_NDKHelper */

#ifndef _Included_com_example_ndktestapplication_NDKHelper
#define _Included_com_example_ndktestapplication_NDKHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndktestapplication_NDKHelper
 * Method:    getNDKPrint
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_ndktestapplication_NDKHelper_getNDKPrint
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
